# Vectorizing vs Non-Vectorizing

In [17]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("C: " , c)
print("Vectorized Version: " + str(1000 * (toc-tic)) + "ms." )

c = 0
tic = time.time()
for i in range(1000000) :
    c += a[i] * b[i]
toc = time.time()

print("C: " , c)
print("Non-Vectorized Version : " + str(1000 * (toc-tic)) + "ms." )
    

C:  250315.3685395242
Vectorized Version: 1.0046958923339844ms.
C:  250315.36853952688
Non-Vectorized Version : 530.6520462036133ms.


# Broadcasting Example 

In [24]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [27]:
cal = A.sum(axis = 0)  # axis = 0 means sum vertically. Use axis = 1 for sum horizontally
print(cal)

[ 59.  239.  155.4  76.9]


In [28]:
percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [30]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
C = np.array([100,200,300])

D = np.array([[100],[200],[300],[400]])

print(C)
print(D)

[100 200 300]
[[100]
 [200]
 [300]
 [400]]


In [32]:
c = B + C #Broadcasting occurs as B is a 3x4 matrix while C is 3x1 matrix.

print(c)

[[101 202 303]
 [104 205 306]
 [107 208 309]
 [110 211 312]]


In [33]:
d = B + D #Broadcasting occurs as B is a 3x4 matrix while D is 1x4 matrix.

print(d)

[[101 102 103]
 [204 205 206]
 [307 308 309]
 [410 411 412]]


# Python - NumPy Vectors

In [34]:
import numpy as np

a = np.random.randn(5)

In [35]:
print(a)

[-1.6769122   0.22536596 -1.05845725 -0.04149236  1.17539263]


In [36]:
print(a.shape)

(5,)


In [44]:
print(a.T)
# Same as 'a' vector. Thus we should rather use np.random.randn(5,1)

[[ 0.65286622 -1.84702416 -2.30077549  1.69122475  0.21766878]]


In [39]:
a = np.random.randn(5,1) 

In [40]:
print(a)

[[ 0.65286622]
 [-1.84702416]
 [-2.30077549]
 [ 1.69122475]
 [ 0.21766878]]


In [41]:
print(a.T)

[[ 0.65286622 -1.84702416 -2.30077549  1.69122475  0.21766878]]


In [42]:
print(a.shape)

(5, 1)


In [43]:
print(np.dot(a,a.T))

[[ 0.4262343  -1.20585968 -1.5020986   1.1041435   0.14210859]
 [-1.20585968  3.41149824  4.24958792 -3.12373296 -0.4020395 ]
 [-1.5020986   4.24958792  5.29356787 -3.89112845 -0.500807  ]
 [ 1.1041435  -3.12373296 -3.89112845  2.86024114  0.36812683]
 [ 0.14210859 -0.4020395  -0.500807    0.36812683  0.0473797 ]]


In [51]:
a = np.random.randn(3, 3)
print(a)
b = np.random.randn(3, 1)
print(b)
c = a*b
print(c)

[[-0.10221801 -0.79130178 -1.04301323]
 [ 1.04507804 -0.59902859  0.99799958]
 [-1.20582512  1.66570963 -0.70870319]]
[[-0.52574445]
 [-0.58306128]
 [-0.54400225]]
[[ 0.05374055  0.41602252  0.54835842]
 [-0.60934454  0.34927038 -0.58189491]
 [ 0.65597158 -0.90614979  0.38553613]]


In [54]:
a = np.random.randn(8, 5) # a.shape = (12288, 150)
b = np.random.randn(5, 2 ) # b.shape = (150, 45)
c = np.dot(a,b)

In [55]:
print(c)

[[ 2.96366654 -3.69893663]
 [ 2.36234741 -2.54915973]
 [-1.58475445  2.48744314]
 [-1.44372975 -1.34774991]
 [-1.54181893  1.75739881]
 [ 1.74262208 -1.63110379]
 [ 1.34649058 -0.9079098 ]
 [-2.28392778  3.36835218]]


In [1]:
l1= [1,2,3]

In [2]:
l2= [2,4,6]

In [3]:
l1 == l2

False

In [4]:
2*l1 == l2

False

In [5]:
2*l1

[1, 2, 3, 1, 2, 3]

In [6]:
2**l1

TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'list'

In [7]:
l2 % l1

TypeError: unsupported operand type(s) for %: 'list' and 'list'

In [ ]:
if